### ISSUE TITLE
HEAD request on container for object commands

### ISSUE THREAD

**Issue by jamiehannaford** [rackspace/rack#303]
If you upload a new file to a container that does not exist, you get back this error message:

> error I couldn't find object [blah] in container [wp_test1]

which is confusing, because it gives the impression the operation failed because the _object_ doesn't exist, rather than the container. we should probably change it to something like:

> error The [wp_test1] container does not exist

maybe we could type hint the [ObjectNotFoundError](https://github.com/rackspace/rack/blob/master/internal/github.com/rackspace/gophercloud/openstack/objectstorage/v1/objects/errors.go#L30-L32) if any error occurs during the upload.

**Comment by jrperritt** [comment]
Hmm, this should get caught at the `HEAD` request and fail before it has an opportunity to upload a file. I'll have a look.

**Comment by jrperritt** [comment]
I think I see the issue. Rackspace is sending back a 404 for the container, but because it's an `object` request, it's being interpreted as a 404 on the object. One option is making a `HEAD` request in the `HandleFlags` method of all the `object` commands to make sure the container exists. Of course, it's _possible_ that the `HEAD` request succeeds and the container gets deleted before `Execute` completes, but I think that's an extremely unusual case.
