### ISSUE TITLE
Support for large objects.

### ISSUE THREAD

**Issue by mxxcon** [rackspace/rack#345]
As mentioned in #344, `rack` does not seem to support working with or at least uploading large objects/files over 5GB in size.
Please add support for such files.

**Comment by StephenBrown2** [comment]
Perhaps something like the method used here could be employed?
Source: https://www.socketloop.com/tutorials/golang-how-to-split-or-chunking-a-file-to-smaller-pieces

---

Problem :

You have a big file and you want to split / chunk the file into smaller pieces. How to do that in Golang?

Solution :

Calculate the size of each chunk that you want to split the file into.
Read the file content into a buffer(created according to the calculated chunk size).
Write the buffer content into individual pieces.
Here you go :
```
 package main

 import (
         "fmt"
         "io/ioutil"
         "math"
         "os"
         "strconv"
 )

 func main() {

         fileToBeChunked := "./somebigfile"

         file, err := os.Open(fileToBeChunked)

         if err != nil {
                 fmt.Println(err)
                 os.Exit(1)
         }

         defer file.Close()

         fileInfo, _ := file.Stat()

         var fileSize int64 = fileInfo.Size()

         const fileChunk = 1 * (1 << 20) // 1 MB, change this to your requirement

         // calculate total number of parts the file will be chunked into

         totalPartsNum := uint64(math.Ceil(float64(fileSize) / float64(fileChunk)))

         fmt.Printf("Splitting to %d pieces.\n", totalPartsNum)

         for i := uint64(1); i < totalPartsNum; i++ {

                 partSize := int(math.Min(fileChunk, float64(fileSize-int64(i*fileChunk))))
                 partBuffer := make([]byte, partSize)

                 file.Read(partBuffer)

                 // write to disk
                 fileName := "somebigfile_" + strconv.FormatUint(i, 10)
                 _, err := os.Create(fileName)

                 if err != nil {
                         fmt.Println(err)
                         os.Exit(1)
                 }

                 // write/save buffer to disk
                 ioutil.WriteFile(fileName, partBuffer, os.ModeAppend)

                 fmt.Println("Split to : ", fileName)
         }
 }
```
Sample output :
```
Splitting to 5 pieces.
Split to : somebigfile_1
Split to : somebigfile_2
Split to : somebigfile_3
Split to : somebigfile_4
```
References :

https://www.socketloop.com/tutorials/golang-convert-cast-int64-to-string

https://www.socketloop.com/tutorials/golang-upload-big-file-larger-than-100mb-to-aws-s3-with-multipart-upload

---

Of course, a manifest file would need to be generated and uploaded as well, probably best to use a static manifest, since #344 mentioned that one does calculate the hash of the file uploads, but a dynamic manifest would be easier.

**Comment by jrperritt** [comment]
I think we can do better. We should be able to delegate the buffering to the standard library (if we choose to) _and_ upload the individual pieces concurrently. I should have something to test this week.

**Comment by StephenBrown2** [comment]
Cool. Looking forward to it.
