### ISSUE TITLE
rack help should display global flags 

### ISSUE THREAD

**Issue by everett-toews** [rackspace/rack#442]
Currently the only way I know how to view the global flags is to use `--help` on a specific command like `rack servers instance list --help`

Since the global flags are global, they should be displayed when asking `rack` for help on the global scope with `rack help`.

**Comment by jrperritt** [comment]
I disagree. Using `help` or `--help` after any command or subcommand should (and does) give you your options for the next term. Because global flags (like the local flags) can only be used after the last subcommand, they're only displayed after the final fixed term (e.g. `rack servers instance list --help`).
